config/routes.rb
Rails.application.routes.draw do
  resources :essences

end

app/models/essence.rb
class Essence < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/essences_controller.rb
class EssencesController < ApplicationController
  before_action :set_essence, only: [:show, :edit, :update, :destroy]

  # GET /essences
  # GET /essences.json
  def index
    @essences = Essence.all
  end

  # GET /essences/1
  # GET /essences/1.json
  def show
  end

  # GET /essences/new
  def new
    @essence = Essence.new
  end

  # GET /essences/1/edit
  def edit
  end

  # POST /essences
  # POST /essences.json
  def create
    @essence = Essence.new(essence_params)

    respond_to do |format|
      if @essence.save
        format.html { redirect_to @essence, notice: 'Essence was successfully created.' }
        format.json { render :show, status: :created, location: @essence }
      else
        format.html { render :new }
        format.json { render json: @essence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /essences/1
  # PATCH/PUT /essences/1.json
  def update
    respond_to do |format|
      if @essence.update(essence_params)
        format.html { redirect_to @essence, notice: 'Essence was successfully updated.' }
        format.json { render :show, status: :ok, location: @essence }
      else
        format.html { render :edit }
        format.json { render json: @essence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /essences/1
  # DELETE /essences/1.json
  def destroy
    @essence.destroy
    respond_to do |format|
      format.html { redirect_to essences_url, notice: 'Essence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_essence
      @essence = Essence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def essence_params
      params.require(:essence).permit(:title, :description, :exp, :img_url, :price, :type, :locate, :rating, :exp)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/essences_helper.rb
module EssencesHelper
end

app/views/essences/_form.html.erb
<%= form_for(@essence) do |f| %>
  <% if @essence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@essence.errors.count, "error") %> prohibited this essence from being saved:</h2>

      <ul>
      <% @essence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :exp %><br>
    <%= f.text_area :exp %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br>
    <%= f.text_field :img_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>

  <div class="field">
    <%= f.label :locate %><br>
    <%= f.text_field :locate %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :exp %><br>
    <%= f.text_area :exp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/essences/edit.html.erb
<h1>Editing essence</h1>

<%= render 'form' %>

<%= link_to 'Show', @essence %> |
<%= link_to 'Back', essences_path %>

app/views/essences/index.html.erb
<h1>Listing essences</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Exp</th>
      <th>Img url</th>
      <th>Price</th>
      <th>Type</th>
      <th>Locate</th>
      <th>Rating</th>
      <th>Exp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @essences.each do |essence| %>
      <tr>
        <td><%= essence.title %></td>
        <td><%= essence.description %></td>
        <td><%= essence.exp %></td>
        <td><%= essence.img_url %></td>
        <td><%= essence.price %></td>
        <td><%= essence.type %></td>
        <td><%= essence.locate %></td>
        <td><%= essence.rating %></td>
        <td><%= essence.exp %></td>
        <td><%= link_to 'Show', essence %></td>
        <td><%= link_to 'Edit', edit_essence_path(essence) %></td>
        <td><%= link_to 'Destroy', essence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Essence', new_essence_path %>

app/views/essences/new.html.erb
<h1>New essence</h1>

<%= render 'form' %>

<%= link_to 'Back', essences_path %>

app/views/essences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @essence.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @essence.description %>
</p>

<p>
  <strong>Exp:</strong>
  <%= @essence.exp %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @essence.img_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @essence.price %>
</p>
<p>
  <strong>Type:</strong>
  <%= @essence.type %>
</p>
<p>
  <strong>Locate:</strong>
  <%= @essence.locate %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @essence.rating %>
</p>

<p>
  <strong>Exp:</strong>
  <%= @essence.exp %>
</p>

<%= link_to 'Edit', edit_essence_path(@essence) %> |
<%= link_to 'Back', essences_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Voxpopam</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>